name: send-gold-signal
on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes (UTC)
  workflow_dispatch:         # allows manual run

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python send_signal.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          METALPRICE_KEY: ${{ secrets.METALPRICE_KEY }}
